server:
  port: 8080

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456

logging:
  level.root: info
  level.com.haiyang: debug
  path: logs/
  file: flowable-test.log


---
logging:
  level.root: warn
  path: logs/
  file: flowable-test.log
